#!/bin/bash
set -euo pipefail
cd "$(dirname $0)"

find . -name *.symlink | while read symlink ; do 
    f=$(basename ${symlink%.*})
    echo "Linking $f"
    sh -c "ln -s $(realpath $f) $HOME/\.$f" || true
done

find . -name install.sh | while read installer ; do 
    sh -c "${installer}" || true
done

