#!/bin/bash
set -euo pipefail
cd "$(dirname $0)"
set +e
find $(pwd) -name "*.symlink" | while read symlink ; do 
    f=${symlink%.*}
    echo "Linking $f"
    sh -c "ln -s $symlink $HOME/.$(basename $f)" || true
done
set -e
find . -name install.sh | while read installer ; do 
echo
    bash -xe "${installer}" || true
done

