alias tflint='docker run -v $(pwd):/data --workdir=/data -t wata727/tflint'
alias pandoc='docker run -v `pwd`:/source jagregory/pandoc'
alias lr='ls -tr'
alias cd..='cd ..'
alias dstat='dstat -cnry'   
alias clipboard='xclip -i -selection clipboard'
alias rename='perl-rename'
alias mc='mc -b'
alias sl='ls'
alias g='git'
alias ll='ls -GFhl'
alias em='emacs -nw'
alias du="du -h"              
alias lss='ls -bash'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias grep="egrep --color=auto"
